### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by scottswezey** [scottswezey/twilio_magic_values#1]
- [x] Implement automated tests that hit the Twilio testing API and confirm expected responses.
- [x] Improve module docs
- [x] improve readme
- [x] Close and merge #2 - (Improved function names)
- [x] Close and merge #3 - (Docs which mention a Twilio error code should link to it)
- [x] Give code examples showing the proper use of this library in readme
- [x] Clean up the docs. Most of it is poorly written. (ex: "valid to call **_to_**")

**Comment by scottswezey** [comment]
All done. Can't think of anything else. Will close and push `1.0.0-beta1` momentarily.
